### ISSUE TITLE
Deploy test boxes without influencing test outcome

### ISSUE THREAD

**Issue by ppp0** [cargomedia/puppet-packages#993]
E.g

We do require `apt::upgrade` in `provision.pp` right now but this influences the outcome of testing different apt transports

May be deploy boxes with a shell script? Postpone first puppet execution to the test spec?

To be discussed @tomaszdurka 

@njam @kris-lab  cc

**Comment by njam** [comment]
I would suggest to do a shell script, should be pretty simple!

**Comment by ppp0** [comment]
+1 for shell provisioning

**Comment by tomaszdurka** [comment]
As discussed this ain't so simple.

Before we do tests we require a few specific package, configurations to be present.
- polipo (for caching)
- puppet (common entities needed in order to run puppet apply correctly)

We also require `apt-update`, but that is only for some performance reasons - which imo we should skip.

**Comment by tomaszdurka** [comment]
We are afraid that by applying puppet modules we might modify 3rd party things. With shell script we could have exact same problem.
So instead of making provisioning in the shell script I would propose to make sure those scripts are isolated and don't install 3rd party things. Maybe we should add some specs, to make sure they don't trigger apt-get updates, etc.

**Comment by ppp0** [comment]
Somewhat agree

* for performance reasons we require `polipo` and for nothing else
* `apt-get upgrade` is required in order to always use the same (latest) set of packages

I would opt for not using puppet to provision the box but only when spec testing (ie applying the manifests we want to test). 

Also discussed was to only deploy the modules listed in `Puppetfile` in order to make sure it contains all needed dependencies

**Comment by tomaszdurka** [comment]
Will be solved in #997
